# Μία εισαγωγή στην Numpy σε 10 λεπτά!

**Πλειάδες, Λίστες και Διανύσματα**

Στο παρόν κεφάλαιο θα κάνουμε μία σύντομη εισαγωγή στην βιβλιοθήκη της python, η οποία θα μας επιτρέψει να  ορίσουμε διανύσματα, πλειομεταβλήτές συναρτήσεις και πίνακες. Στην μικροοικονομική θεωρία βασικές έννοιες όπως οι τιμές και οι ποσότητες αγαθών ορίζονται ως πολυδιάστατα διανύσματα και πίνακες,ενώ η ανάλυσή μας πολλές φορές απαιτεί κάποια στοιχειώδη εργαλεία άλγεβρας. Θα ξεκινήσουμε την παρουσίασή μας με κάποιες δομές στοιχείων που είναι ενσωματωμένες στην Python, όπως οι πλειάδες (**tuples**) και οι λίστες (**lists**), και στην συνέχεια θα ορίσουμε την βασική δομή που χρησιμοποιούμε στην βιβλιοθήκη της Numpy,  το διάνυσμα (**array**).

Μία πλειάδα είναι μια συμβολοσειρά σταθερού μήκους και τα ορίσματά της μπορεί να αριθμοί ή και γράμματα. Ορίζουμε μια πλειάδα ως εξής:

In [1]:
a=('b', 2, 3, 'apple')
a

('b', 2, 3, 'apple')

In [2]:
type(a)

tuple

Παραπάνω έχουμε ορίσει μια πλειάδα, αποτελούμε από  τέσσερα στοιχεία, τα οποία διατάσουμε διαχωρισμένα από κόμματα και περικλειόμενα σε παρενθέσεις. Έχουμε ορίσει την πλειάδα με το γράμμα $a$,  και όπως μπορείτε να παρατηρήσετε στο παραπάνω κελί, τα ορίσματα του είναι αριθμοί , γραμμάτα και ολόκληρες λέξεις. Εφόσον, έχουμε ορίσει την πλειάδα μπορούμε να επικαλέστούμε τα μεμονωμένα στοιχεία του. Η πλειάδα μας έχει τέσσερα διατεταγμένα στοιχεία το πρώτο στοιχείο είναι το γραμμά 'b', ακολουθούμενο από τους αριθμούς 2 και 3, ενώ το τελευταίο στοιχείο είναι η λέξη 'apple'. Στο κελί 2, επιβεβαιώνουμε ότι το a  είναι όντως μια πλειάδα, χρησιμοποιώντας την εντολή  type().

Σε κάθε συμβολοσειρά στην Python το πρώτο στοιχείο είναι στην θέση 0. Επομένως, αν επικαλεστω το στοιχείο στην θέση 0, η Python θα μου επιστρέψει το πρώτο στοιχείο, δηλαδή το 'b'. 

In [3]:
a[0]

'b'

Όμοια, αν επικαλεστώ το δεύτερο στοιχείο, η Python μου επιστρέφει τον αριθμό 2.

In [4]:
a[1]

2

Σε κάθε περίπτωση, εφόσον μπορώ να επικαλεστώ τα μεμονωμένα στοιχεία της πλειάδας, θα μπορούσα και να τα επαναπροσδιορίσω. Για παράδειγμα, θα ήθελα να αλλάξω το πρώτο στοιχείο της πλειάδας a με τον αριθμό 10. Δυστυχώς, στις πλειάδες δεν μπορούμε να επαναπροσδιορίσουμε τα στοιχεία της συμβολοσειράς, και όπως προείπαμε δεν μπορούμε να αλλαξουμε και την διάστασή της. Ωστόσο, ευτυχώς τις δυνατότητες αυτές μας τις παρέχει μια παρόμοια συμβολοσειρά, η λίστα. Στον ορισμό μιας λίστας τα στοιχεία της συμβολοσειράς περικλείονται σε αγκύλες και όχι σε παρενθέσεις. Ακολούθως ορίζω την λίστα b.

In [5]:
b=[1,2,3,'q']
b

[1, 2, 3, 'q']

Αν επιθυμώ να αλλάξω το τελευταίο στοιχείο της λίστας b, το οποίο είναι το γράμμα 'q', με τον αριθμό 10, πλέον είμαι σε θέση να το κάνω. Το τελευταίο στοιχείο της λίστας β είναι στην θέση 3. Θυμηθείτε ότι πάντα ξεκινάμε την αρίθμηση από την θέση 0,
$$b=[1,2,3, 'q']$$
με αύξοντα αριθμό θέσεων
$$b=[0,1,2,3].$$

In [6]:
b[3]=10
b

[1, 2, 3, 10]

Στο κελί 6, όρισα το στοιχείο της λίστας b στην θέση 3, να είναι το στοιχείο 10. Επικαλούμενος εκ νέου την λίστα, η αντικάτάσταση έχει πραγματοποιηθεί.

Ένας διαφορετικός τρόπος να επικαλούμε τα στοιχεία μια λίστας είναι αναφορικά από το τελευταίο στοιχείο της και όχι το πρώτο. Όπως είδαμε παραπάνω το τελευταίο στοιχείο της λίστας b είναι το $b[3]$. Στην Python, μπορούμε να επικαλεστούμε το τελευταίο στοιχείο μια λίστας με την θέση -1. Συγκεκριμένα,

In [7]:
b[-1]

10

Όμοια, το προ-τελευταίο στοιχείο της λίστας είναι το -2, κοκ..

#### Ένωση και τεμαχισμός λίστας

Ας ορίσουμε μια νέα λίστα.

In [8]:
c=[11,12,13]

Μπορώ να ορίσω μια καινούργια λίστα, την οποία θα ονομάσουμε λίστα d, η οποία θα αποτελείται από τα στοιχεία των λιστών b  και c.

In [9]:
d=b+c
d

[1, 2, 3, 10, 11, 12, 13]

Η νέα λίστα αποτελείται απο τα 4 στοιχεία της b και τα 3 στοιχεία της c. Αν επιθυμούσα να προσθέσω ακόμη ένα στοιχείο στο τέλος της λίστας d, για παράδειγμα το στοιχείο 5, θα μπορούσα να χρησιμοποιήσω την εντολή append().

In [10]:
d.append(5)
d

[1, 2, 3, 10, 11, 12, 13, 5]

Στην νέα μορφή της η λίστα d έχει ένα επιπλέον στοιχείο. Ωστόσο πολλές φορές θα ήταν χρήσιμο για εμένα οι αριθμοί στην λίστα να είναι σορταρισμένοι σε αύξον μέγεθος. Επομένως, οι αριθμοί στην λίστα να εμφανίζονται από τον μικρότερο προς τον μεγαλύτερο. Η εντολή που χρησιμοποιούμε ώστε να επιτύχουμε το αύξον σορτάρισμα είναι η εντολή sort().

In [11]:
d.sort()
d

[1, 2, 3, 5, 10, 11, 12, 13]

Ένα άλλο χρήσιμό εργαλείο που μας παρέχει η  Python είναι ότι οι συμβολοσειρές της επιδέχονται τιμές αληθοφάνειας, επομένως μπορούμε να δούμε αν ικανοποιούν κάποια κριτήρια ή χαρακτηριστικά ή όχι. Ένα απλό παράδειγμα είναι το ακόλουθο. Θα επιθυμούσα να γνωρίζω αν ο αριθμό 7 περιέχεται στην λίστα μου.

In [12]:
7 in d

False

Όπως ήταν αναμενόμενο, ο αριθμός 7 δεν είναι στην λίστα μου. Αντίθετα, μπορώ να επιβεβαιώσω ότι ο αριθμός 5 είναι στην λίστα μου.

In [13]:
5 in d

True

Πάμε τώρα να δούμε ένα άλλο ενδιαφέρον εργαλείο που μπορούμε να χρησιμοποιήσουμε με τις λίστες, τον *τεμαχισμό*. Η λίστα d που έχω κατασκευάσει αποτελείται από 8 στοιχεία ή είναι μήκους 8. Αν δεν είμαι σίγουρος για το μήκος της λίστας μου μπορώ να χρησιμοποιήσω την εντολή len().

In [14]:
len(d)

8

Εστω ότι θα επιθυμούσα να κρατήσω μόνο τα 5 πρώτα στοιχεία.

In [15]:
d[0:5]

[1, 2, 3, 5, 10]

Στην περίπτωση αυτή δίνω δύο ορίσματα, Το πρώτο στοιχείο που περιλαμβάνεται και μετά την ανω-κάτω τελεία δίνω το πρώτο στοιχείο που δεν περιλαμβάνεται στην λίστα μου. Όντως, εδω το όρισμα είναι το στοιχείο στην θέση 5 (δηλαδή το έκτο στοιχείο της λίστας) το οποίο είναι ο αριθμός 11. Επίσης το πρώτο στοιχείο που περιλαμβάνεται είναι στην θέση 0 δηλαδή το $d[0]=1$. Προς διευκόλυνση μας, αν ξεκινούμε από την αρχή της λίστας, μπορούμε να αφήσουμε το όρισμα κενό, δηλαδή,

In [16]:
d[:5]

[1, 2, 3, 5, 10]

Τώρα, αν επιθυμώ να τεμαχίσω την λίστα από ένα σημείο διαφορετικό από το πρώτο στοιχείο, για παράδειγμα από το τρίτο στοιχείο (το οποίο βρίσκεται στην θέση 2, $d[2]=3$, η εντολή που θα έδινα θα ήταν

In [17]:
d[2:5]

[3, 5, 10]

Έστω τώρα ότι επιθυμώ να τεμαχίσω την λίστα d απο την θέση 2 έως το τέλος. Η αντίστοιχη εντολή θα ήταν,

In [18]:
d[2:]

[3, 5, 10, 11, 12, 13]

Μπορώ να χρησιμοποιήσω στα ορίσματά μου κατά τον τεμαχισμό ως σημείο αναφοράς το τέλος; Η απάντηση είναι καταφατική. Θυμηθείτε πως αλλάζει η αρίθμηση αναφοράς για την λίστα d,
$$ d=[0,1,2,3,4,5,6,7]$$
ή
$$ d = [-8,-7,-6,-5,-4,-3,-2,-1]$$
Παρατηρούμε ότι $d[2]=3=d[-6]$. Επομένως, θα ήταν

In [19]:
d[-6:]

[3, 5, 10, 11, 12, 13]

##  Η βιβλιοθήκη  Numpy

Ενώ οι λίστες και οι πλειάδες είναι δομές στοιχείων οι οποίες μπορούν να περιλαμβάνουν όποιες  συμβολοσειρές επιθυμούμε η βιβλιοθήκη Numpy χρησιμοποιείται  για την αριθμητική ανάλυση και την χρήση πράξεων άλγεβρας σε χώρους διανυσμάτων. Βασικό στοιχείο της βιβλιοθήκης είναι το πολυδιάστατο διάνυσμα (ndarray) το οποίο δέχεται μόνο αριθμούς ως στοιχεία. Για να μπορέσουμε να ορίσουμε ένα διάνυσμα θα πρέπει πρώτα να επικαλεστούμε την βιβλιοθήκη της Numpy. Ο πιο τυπικό τρόπος για να το κανουε αυτό είναι να χρησιμοποιήσουμε κάποιο alias ώστε να κάνουμε εύκολη χρήση των εντολών της.

In [20]:
import numpy as np

In [21]:
a=np.array([1,2,3])
a

array([1, 2, 3])

Όμοια με τις λίστες, μπορούμε να επαναπροσδιορίσουμε τα στοιχεία του διανύσματος, και να πραγματοποιήσουμε οποιοδήποτε τεμαχισμό.

In [22]:
a[0]=19
a

array([19,  2,  3])

In [23]:
a[1:]

array([2, 3])

Εϊναι εύκολο να μετατρέψουμε μια λίστα σε ένα δίανυσμα της Numpy. Ορίστε την λίστα $f=[1,2,3]$

f=[1,2,3]
f=np.array(f)
type(f)

Με τον ίδιο τρόπο που ορίζουμε διανύσματα μπορούμε να ορίσουμε και πίνακες. Στην συνέχεια ορίζουμε έναν πίνακα 2x2.

In [24]:
A=np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

Παρατηρείστε την σύνταξη για τον ορισμό του πίνακα. Κάθε γραμμές του πίνακα ορίζεται μεσα σε αγκύλες, ενώ οι σειρές είναι διαχωρισμένες με κόμμα. Επιπροσθέτως, παρατηρείστε ότι όλες οι γραμμές του πίνακα περικλείονται επίσης με αγκύλες. Στην συνέχεια μπορούμε να ελέγξουμε την διάσταση του πίνακ αλλά και τον τύπο του.

In [25]:
A.shape

(2, 2)

Στο κελί 30 παρατηρούμε ότι με την εντολή shape πέρνουμε την πληροφορία ότι πρόκειτε για έναν πίνακα δίαστάσεως 2x2,

In [26]:
A.dtype

dtype('int32')

 ενώ στο κελί 31 πληροφορούμαστε ότι τα στοιχεία που αποτελούν τον πίνακα είναι ακέραιοι (32-bit ακέραιοι). Θα μπορούσαμε να ορίσουμε έναν πίνακα ώστε ο τύπος των στοιχείων του να είναι float ή κινητής υποδιαστολής. Για παράδειγμα,

In [27]:
C = np.array([[1,2,3], [4,5,6]], dtype=np.float64)
C


array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
C.dtype

dtype('float64')

Πως μπορώ να επικαλεστώ κάποιο στοιχείο ενός πίνακα; Η λογική δεν είναι πολύ διαφορετική από πριν. Τόσο οι γραμμές όσο και οι στήλες ξεκινούν την αρίθμησή τους από το 0. Επομένως το στοιχείο στην πρώτη γραμμή και πρώτη στήλη είναι το (0,0).

In [29]:
C[0][0]

1.0

Αν ήθελα να επκαλεστώ όλη την πρώτη γραμμή θα πρέπει να αφήσω την στήλη κενή, και εν προκειμένω γράφω στην θέση της στήλη το σύμβολο άνω-κάτω τελεία.

In [30]:
C[0,:]

array([1., 2., 3.])

In [31]:
C[1,:]

array([4., 5., 6.])

Όμοια πράττω, όταν θέλω να επικαλεστώ μια στήλη. Ακολούθως επικαλούμε την πρώτη στήλη.

In [32]:
C[:,0]

array([1., 4.])

### Βασικές πράξεις με πίνακες

Για να προσθέσουμε πίνακες πρέπει να είναι της ίδιας διάστασης. Προηγουμένως ορίσαμε τον πίνακα C με διάσταση 2x3.

In [33]:
C.shape

(2, 3)

Ο ανάστροφος πίνακας $C^T$ υπολογίζεται ως

In [34]:
C.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [35]:
C.T.shape

(3, 2)

Επίσης ορίζουμε τον πίνακα D.

In [36]:
D=np.array([[5,6,5],[8,9,1]], dtype=np.float64)
D

array([[5., 6., 5.],
       [8., 9., 1.]])

Στην συνέχεια προσθέτουμε τους δύο πίνακες.

In [37]:
D+C

array([[ 6.,  8.,  8.],
       [12., 14.,  7.]])

In [38]:
E=D-C
E

array([[ 4.,  4.,  2.],
       [ 4.,  4., -5.]])

Για να πολλαπλασιάσω πίνακες ο αριθμός των στηλών της πρώτης πρέπει να ταυτίζεται με τον αριθμό των γραμμών της δεύτερης. Παραπάνω έχω ορίσει τον πίνακα Ε. Ο αριθμός των στηλών του (3) είναι ίδιος με τον αριθμό των γραμμών της ανάστροφής C (C.T). Η εντολή που θα χρησιμοποιήσουμε για τον πολλαπλασιασμό είναι np.dot()

In [39]:
np.dot(E, C.T)

array([[18., 48.],
       [-3.,  6.]])

Ευκολα παρατηρούμε ότι πολλαπλασιάζοντας του πίνακες Ε*(C.T)  με διαστάσεις αντίστοιχα 2x3 και 3x2, το αποτέλεσμα του πολλαπλασιασμού είναι 2x2. Ένας ισοδύναμος τρόπος για να προχωρήσουμε στον ίδιο υπολογισμό είναι και ο ακόλουθος.

In [40]:
E.dot(C.T)

array([[18., 48.],
       [-3.,  6.]])

 **Λύση ενός συστήματος δύο εξισώσεων**

Ας υποθέσουμε ότι έχουμε το ακόλουθο σύστημα εξισώσεων
$$ 2x + 3y =8 $$
$$ x  + 6y =1 $$

Θα μπορούσαμε να το γράψουμε σε μορφή πινάκων στην γενική μορφή $A \cdot X=b$ οπου 

$$ A =\begin{bmatrix}
2 & 3 \\
1 & 6 
\end{bmatrix} $$
και $X^T=(x,y)$, $b^T=(8,1)$.  Η λύση απαιτεί την αντίστροφη της Α, καθώς $X=A^{-1}b$.

In [41]:
A=np.array([[2,3], [1,6]])
b=np.array([8,1])


In [42]:
Ainv =np.linalg.inv(A)
Ainv

array([[ 0.66666667, -0.33333333],
       [-0.11111111,  0.22222222]])

In [44]:
X=Ainv.dot(b)
X

array([ 5.        , -0.66666667])

Ένας πιο εύκολος τρόπος είναι να χρησιμοποιήσουμε απευθείας την έτοιμη εντολή της Numpy, linalg.solve(A, b).

In [47]:
X= np.linalg.solve(A, b)
X

array([ 5.        , -0.66666667])